apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: node-express
  name: node-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: node-express
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-express
        app.kubernetes.io/part-of: node-express
    spec:
      containers:
      - image: node-express:latest
        imagePullPolicy: IfNotPresent
        name: node-express
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3