apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-express
  name: node-express
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app.kubernetes.io/name: node-express